//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBAUsersHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANYOBJECTS
    {
        public string ID { get; set; }
        public int TYPE { get; set; }
        public string COMPANY { get; set; }
        public int IMPORTSTATUS { get; set; }
    }
}
