//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBAUsersHelper
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EBAEntities : DbContext
    {
        public EBAEntities(string connstr)
            : base(connstr)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COMPANIES> COMPANIES { get; set; }
        public virtual DbSet<COMPANYOBJECTS> COMPANYOBJECTS { get; set; }
        public virtual DbSet<OSDEPARTMENTS> OSDEPARTMENTS { get; set; }
        public virtual DbSet<OSGROUPCONTENT> OSGROUPCONTENT { get; set; }
        public virtual DbSet<OSGROUPS> OSGROUPS { get; set; }
        public virtual DbSet<OSMANAGERKEYS> OSMANAGERKEYS { get; set; }
        public virtual DbSet<OSMANAGERS> OSMANAGERS { get; set; }
        public virtual DbSet<OSPOSITIONS> OSPOSITIONS { get; set; }
        public virtual DbSet<OSPROFESSIONS> OSPROFESSIONS { get; set; }
        public virtual DbSet<OSPROPERTIES> OSPROPERTIES { get; set; }
        public virtual DbSet<OSPROPERTYTYPES> OSPROPERTYTYPES { get; set; }
        public virtual DbSet<OSPROPERTYVALUES> OSPROPERTYVALUES { get; set; }
        public virtual DbSet<OSUSERS> OSUSERS { get; set; }
    }
}
