//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBAUsersHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class OSPOSITIONS
    {
        public string ID { get; set; }
        public string DESCRIPTION { get; set; }
        public string USERID { get; set; }
        public int STATUS { get; set; }
        public int TYPE { get; set; }
        public string IMPORTEDPOSCODE { get; set; }
        public Nullable<int> IMPORTSTATUS { get; set; }
    }
}
