//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBAUsersHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class OSPROPERTYTYPES
    {
        public string PNAME { get; set; }
        public string PCAPTION { get; set; }
        public string PDESCRIPTION { get; set; }
        public int PTYPE { get; set; }
        public string PDEFAULTVALUE { get; set; }
        public string PPARAMS { get; set; }
    }
}
