//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBAUsersHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class OSPROPERTIES
    {
        public int OSID { get; set; }
        public string PNAME { get; set; }
        public int PORDER { get; set; }
        public int PREQUIRED { get; set; }
    }
}
