//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBAUsersHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class OSUSERS
    {
        public string ID { get; set; }
        public string FIRSTNAME { get; set; }
        public string LASTNAME { get; set; }
        public string PASSWORD { get; set; }
        public string EMAIL { get; set; }
        public int STATUS { get; set; }
        public int TYPE { get; set; }
        public Nullable<int> IMPORTSTATUS { get; set; }
        public Nullable<System.DateTime> BIRTHDATE { get; set; }
        public Nullable<System.DateTime> EMPLOYEMENTSTART { get; set; }
        public Nullable<System.DateTime> EMPLOYEMENTEND { get; set; }
        public Nullable<int> CATEGORY { get; set; }
        public Nullable<int> SEX { get; set; }
        public string DEPARTMENT { get; set; }
        public string PROFESSION { get; set; }
    }
}
